const projects = [
  {year:'2024',client:'Health Insurance Client',title:'Transforming workflow with process and a cohesive design system.',tags:['Design System','Desktop'],color:'violet',role:'Product Designer II',team:'4 UX designers, 2 Product Owners, 1 Tech Lead, 15+ Developers',timeline:'Continuous evolution — 3 years',description:'As part of a large project to modernize their ecosystem, a large health insurance provider hired 1–5 UX designers at UST Global for 3+ years. I led the evolution of a shared library into a clearer, more comprehensive design system across 100+ handoffs and 7+ teams.',sections:[
    ['Challenge & goals',["The product was an internal, multi-application dashboard where health insurance employees would perform various tasks depending on their role.","After workshops with the UX team, we found extended timelines, inconsistent user experience during development, and reluctance in product and tech teams to adapt to change. Stakeholder interviews connected this to unclear responsibilities and processes, limited design-guideline visibility, and non-scalable code.","I worked across teams to define a governance process, refine the component library, and increase visibility of component guidelines and scalable code. The result was greater clarity and reusability, better alignment around responsibilities, and more consistent design and development.","We set four goals: refine the design library; create a source of truth for code and design guidelines; scale global component code for reuse; and improve design and governance processes."]],
    ['Refine our design library',["With 100+ handoffs from multiple UX designers, we needed to get ahead of consistency for CSS styles, components, and component guidelines so handoffs would be cohesive across products.","I led weekly interface-audit meetings. We discussed where components were used and aligned on guidelines that could meet all products’ needs. For example, we reviewed every popup type, listed inconsistencies, and made decisions that worked across teams.","The audits produced more consistent, flexible components; stronger awareness of usage and user context; notes that explained design decisions; and more frequent consideration of empathy, edge cases, and the impact of component choices."]],
    ['Create a source of truth',["Designers and developers needed one place to view component guidelines and variations, integration status, and completed code that could be reused. This would reduce repeated component questions and increase consistency.","Because guidelines could not live on the demo site, we hosted them on Sketch artboards and linked completed component code in Jira. After successfully advocating for Figma and Dev Mode, these guidelines moved to Figma, where cleaner components, clearer annotations, and more visible code references could be created.","Updating this source of truth improved clarity, awareness of global-versus-local component process, and reuse over hard-coding for the components that had completed code."]],
    ['Scale & governance',["Our components needed to be updateable simultaneously by one developer, without rework across teams, so we could adapt quickly to changing requirements or user feedback. The tech team deemed simultaneous updates infeasible, so we documented the decision and presented the future benefits of a design system.","A governance team included a head representative from each team; I became the head for the design team. I partnered with a Product Owner on a process map for global and product components, including how to handle past handoffs, feasibility constraints, defects, and decision ownership.","The process map created greater clarity and confidence in ambiguous situations. It increased accountability, confidence, efficiency, communication, collaboration, and consistency."]],
    ['Reflection',["I attended Zeroheight’s conference and a master workshop with Brad Frost to learn more about atomic design and advocating for design systems. My research and work led to a presentation for 100+ designers at UST Global about design-system value and advocacy.","I considered conversations with business and technical stakeholders user research: they revealed what this specific client needed from a design system. Although budget and the technical framework could not support a complete system, we delivered a blueprint and foundation for future progress."]]
  ]},
  {year:'2023',client:'Health Insurance Client',title:'Creating a common entry experience for users across teams.',tags:['Desktop'],color:'lime',role:'Senior Product Designer',team:'3 designers, Product Owner, 14 stakeholders',timeline:'3 months',description:'A central entry experience for a large health-provider’s internal, multi-application dashboard — designed to make scattered information, resources, and work more visible and actionable.',sections:[
    ['Challenge',["A large health provider was modernizing a multi-application internal dashboard with a five-person UST Global UX team. Information was scattered across 35+ plans, real-time updates were difficult to find, and tools were not integrated into a clear workflow.","The design principles were centralization, workflow integration, and visibility: give users a useful place to start, connect it to their work, and surface what needs attention."]],
    ['Ideation',["We explored education and help, a customizable dashboard, and notifications and alerts. The opportunity was to create one entry point that could orient users quickly while supporting the needs of different teams.","Across five workshops with 11 participants, we gathered 259 insights and ideas and turned them into 26 user stories. These sessions helped stakeholders align on priorities and made complex workflows visible."]],
    ['Solution',["The resulting entry experience brought together a help center, guides and resources, customizable widgets, and notifications. It was designed to make relevant information easier to find without overwhelming users.","Widgets gave teams a flexible dashboard; guides and resources supported education at the moment of need; and alerts made important changes visible in the flow of work."]],
    ['Learnings & reflection',["I pitched a high-impact innovation while balancing many stakeholder needs. Facilitating workshops, synthesizing input, and taking initiative helped the group move from a broad problem space toward a practical, shared direction."]]
  ]},
  {year:'2022',client:'TrueToForm',title:'Utilizing AI-powered 3D tech to enhance real-time experiences.',tags:['UX Research','AI','Startup','Design System','Desktop','Mobile'],color:'coral',role:'UX Research & UX/UI Design',team:'CEO & CTO, creative design lead, 2 developers',timeline:'Startup product work',description:'At TrueToForm, I used user testing to uncover issues slowing task time and causing functional failures. Real-time feedback and an offline design produced major improvements in task efficiency and success.',sections:[
    ['Background research',["Most clothing is made for model body types, leading to poor fit. TrueToForm uses modern smartphone cameras to capture accurate body measurements in 30 seconds and create digital models that help designers make better-fitting custom clothing.","Before I joined, the CEO had interviewed 50+ fashion designers and customers. I created an affinity map from those notes to summarize recurring categories, identify follow-up questions, and brainstorm feature opportunities.","Six detailed personas were too complex for practical use. With the Creative Design Lead, I reduced them to two simple, generic personas — Scanner and Individual Designer — which clarified user identity and product purpose."]],
    ['Usability testing',["I traveled to Chicago to conduct in-person testing of the Scanner’s primary flow in a fashion school, a tailor shop, and participants’ homes. Professional tailors also measured participants. Diverse body types and locations helped reduce sampling bias and supported model training.","Users interpreted device placement, body position, and movement timing differently, causing scans to fail often. We improved instructions with boundary lines, real-time visual and voice feedback, hands-free auto-start, and greater tolerance for minor movement. This drastically improved task time and scan success rate.","Low WiFi signal in large public buildings caused long upload delays and functional bugs. We reduced reliance on WiFi through an offline design."]],
    ['Offline design',["I began with low-fidelity wireframes to quickly explore flows and present options. We realized that submissions could be queued whenever possible, so users could leave the app without restarting the scan process, whether connected or not.","Rather than requiring connection to validate a share code, submit an avatar, and share it, data is sent in one queued submission. A simple share-status toast communicates whether it is sharing or complete, eliminating extra screens.","The approach reduced screens, increased accessibility for users without reliable WiFi, eliminated many connection-related errors, and saved users time by allowing them to multitask while a submission completed."]],
    ['End result',["The primary flow — including scan feedback and offline design — increased primary task success rate by 70% and decreased primary task time by 40%. Users can now complete more accurate scans more successfully, regardless of connection strength."]],
    ['Learnings',["Every company has different starting points, needs, and processes; not every traditional design step is necessary. Existing research can still be synthesized into useful insights and a more focused vision.","Testing had to balance research integrity with the founders’ need for accuracy data. I observed without interfering for the first four scans, then helped participants complete later scans. That preserved valuable unbiased observations while supporting business needs."]]
  ]},
  {year:'2025',client:'Health Insurance Client',title:'Client 360.',tags:['UX Research','Design System','Desktop'],color:'violet',role:'Senior Product Designer',team:'Confidential',timeline:'Confidential',description:'A confidential redesign that consolidates broker search, client information, and next steps into a clearer Client 360 experience.',sections:[
    ['Problem',["External brokers sell plans to employers and individuals, use the existing tool several times a day, and often need to start quotes or review applications quickly. They need confidence that <strong>client information and documents are accurate, relevant, and current</strong>—without having to remember where to look.","The initial persona was an <strong>assumption to validate through UX research</strong>. It highlighted a practical tension: brokers needed broad capabilities and fast answers, but the product made them navigate across systems, rely on support, or keep their own workarounds."]],
    ['Users & research',["I organized the available audit notes and stakeholder inputs into a research plan focused on search behavior, information priorities, document confidence, and the handoffs between quoting, applications, and renewals.","The next research phase is designed to validate the assumed broker persona, observe real search and decision-making behavior, and prioritize the highest-value workflows before detailed implementation."]],
    ['Heuristic evaluation',["The existing experience surfaced several repeat patterns: search depended on exact terms; employees could not be found directly from global search; filters were hard to understand; and common next actions were not visible in results.","Client cards were <strong>dense and information-first</strong>, with unclear hierarchy and key details dispersed across tabs and portals. Frequent timeouts, inconsistent controls, generic errors, and navigation that did not preserve context further interrupted broker work."]],
    ['Key insights',["I translated the findings into five product principles: <strong>trust & confidence, prioritization & focus, personalization at scale, decision-first design, and workflow consolidation.</strong>","Together, these principles shift the experience from a place where brokers hunt for data to a product that helps them understand context, see what matters, and take the next step with confidence."]],
    ['Search experience',["<strong>Widespread search and standardized cards</strong> let brokers find members, groups, quotes, applications, and renewals in one place. Search can recognize multiple attributes—such as name, Client ID, quote, or application—across stages of the sales funnel.","Each result card is designed to be easy to scan, retain the relevant context, and surface a clear next step. This reduces manual lookup, page switching, and the need to recall where information lives."]],
    ['Client 360 redesign',["Client 360 brings the most relevant client details into a <strong>single, cohesive view</strong>, with persistent context and clearer grouping. Brokers can access high-frequency actions such as downloading ID cards, opening billing PDFs, and retrieving SBC documents without leaving the workflow.","The goal is not simply to show more data. It is to provide a <strong>reliable source of truth</strong> that supports decisions, reduces navigation time, and gives brokers a path to existing experiences when needed during modernization."]],
    ['Information architecture',["The redesigned information architecture will map the relationship between global search, result cards, client context, documents, and the existing tools that remain part of the end-to-end workflow."]],
    ['Before & after',["The Yasmina record below shows the <strong>before-redesign</strong> experience: a dense record page with key information spread across columns and tabs. The planned comparison will document how the redesigned Client 360 view improves hierarchy, clarity, and access to next actions."]],
    ['Next steps',["The concept establishes a direction for a more coherent broker experience. Next steps include validating the search model and card content with brokers, testing the proposed information architecture, and measuring whether the redesign reduces time-to-information, unnecessary navigation, and reliance on workarounds."]]
  ]},
  {year:'2025',client:'Telesales',title:'Adjusting health plan shopping for telesales agents.',tags:['Desktop'],color:'blue',role:'Product Designer',team:'Confidential',timeline:'In progress',description:'Case Study Details Coming Soon!',sections:[['Currently working on this project',["This UX Leadership and UX/UI Design case study is currently in progress. Full details will be added when they can be shared."]]]},
  {year:'2021',client:'Operational Marketer',title:"Redesigning and rebranding a client’s personal website.",tags:['Design System','Desktop'],color:'lime',role:'UI Designer',team:'Client collaboration',timeline:'Less than 1 month',description:'This client reached out to redesign his existing personal marketing website, Operational Marketer. This case study focuses on visuals for now; additional case-study details are being written.',sections:[
    ['Goals',["Improve the existing UX and UI design with clear information hierarchy and minimal distractions.","Create a bold brand through consistent color and typography.","Create meaningful and consistent icons."]],
    ['The result',["The redesigned system included a landing page, About page, and business cards. Additional materials included business cards and pitch-deck templates."]]
  ]},
  {year:'2020–24',client:'Various Clients',title:'More client projects.',tags:['UX Research','Design System','Desktop'],color:'coral',role:'Product Designer',team:'Cross-functional client teams',timeline:'Selected engagements',description:'A selection of additional client work across UX/UI design, research, and leadership.',sections:[
    ['AG Grid redesign',["Multiple capability teams each needed a data table, but their needs differed: complex tag searching, saved views, simple sorting, and linked rows. AG Grid, MatTable, Fuse Angular, and other third-party frameworks were used in different places, resulting in an inconsistent UI.","We saw an opportunity to increase reusability and consistency while reducing development effort. I held a workshop with the design team to understand diverse user needs and brainstorm one scalable template that could remain simple and easy to use.","We removed unused AG Grid functionality and redundant buttons, icons, and search bars. The cleaner solution supported complex tables while becoming faster to learn and use. We added saved views and an edit mode for creating, renaming, editing, and deleting them.","Brand styles made shadows, dividers, icons, typography, buttons, spacing, padding, and dropdowns consistent with the library. After iteration, I presented the concept and alternatives to business and technical stakeholders, who approved the recommendations."]],
    ['Roles & permissions',["The existing interface created repetitive manual work for security administrators: audit filters were hard to navigate, audit history did not show what changed, role management required backend-admin involvement, and fine-grain permission combinations were difficult to understand.","After stakeholder interviews, the goal was to redesign the process and apply modern UI to improve usability for Security Admins.","The solution introduced a searchable, filterable data table with a simple default view and saved settings; an Audit History page that clearly showed changes; self-service role creation, editing, deletion, and recovery; a progressive wizard for complex input rules; sections and accordions for role details; and permission templates, tiered tables, and hover tooltips to clarify what each role includes."]]
  ]}
];

const projectList=document.querySelector('#project-list');
const applyDefaultVideoSpeed=root=>{const videos=root.matches?.('video')?[root]:Array.from(root.querySelectorAll?.('video')||[]);videos.forEach(video=>{if(video.dataset.defaultSpeedApplied)return;video.dataset.defaultSpeedApplied='true';const setSpeed=()=>{video.defaultPlaybackRate=1.5;video.playbackRate=1.5};setSpeed();video.addEventListener('loadedmetadata',setSpeed)})};
applyDefaultVideoSpeed(document);
new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1)applyDefaultVideoSpeed(node)}))).observe(document.body,{childList:true,subtree:true});
const ttfFrames=['04','05','06','07','08','09','10','11','12'];
const omFrames=['landing','about','business-cards'];
function tagMarkup(tag){
  const icons={
    Desktop:'<svg class="tag-icon" viewBox="0 0 16 16" aria-hidden="true"><rect x="2" y="2.5" width="12" height="8" rx="1.2" fill="none" stroke="currentColor" stroke-width="1.35"/><path d="M6 13h4M8 10.5V13" fill="none" stroke="currentColor" stroke-width="1.35" stroke-linecap="round"/></svg>',
    Mobile:'<svg class="tag-icon" viewBox="0 0 16 16" aria-hidden="true"><rect x="4.6" y="1.5" width="6.8" height="13" rx="1.2" fill="none" stroke="currentColor" stroke-width="1.35"/><path d="M7.2 12.1h1.6" stroke="currentColor" stroke-width="1.35" stroke-linecap="round"/></svg>'
  };
  return `${icons[tag]||''}${tag}`;
}
function projectCarousel(p,i){if(p.client==='TrueToForm')return `<div class="ttf-cycle" aria-label="TrueToForm mobile product flow preview"><div class="ttf-carousel"><div class="ttf-carousel-track">${[...ttfFrames,...ttfFrames].map(n=>`<img src="./assets/ttf-cycle-hq/${n}.png" alt="" />`).join('')}</div></div></div>`;if(p.title==='Client 360.')return `<div class="client360-preview" aria-label="Client 360 desktop product preview"><div class="client360-jane"><img src="./assets/client-360/jane.png" alt="Client 360 record overview" /></div></div>`;if(p.client==='Operational Marketer')return `<div class="om-static-preview" aria-label="Operational Marketer brand and website preview">${omFrames.map((n,index)=>`<div class="om-preview-frame ${index===0?'om-scroll-preview':''}"><img src="./assets/operational-marketer/${n}.png" alt="" /></div>`).join('')}</div>`;return `<div class="case-thumb-carousel case-thumb-${i}" aria-hidden="true"><div class="case-thumb-track">${[0,1,2,3,4,5,0,1,2,3,4,5].map(n=>`<span class="case-thumb-frame frame-${n}"></span>`).join('')}</div></div>`}
function renderProjects(filters=[]){projectList.innerHTML=projects.map((p,i)=>`<button class="project-card ${p.color} ${!filters.length||filters.some(f=>p.tags.includes(f))?'':'is-filtered'}" data-project="${i}"><div class="project-meta"><span>${p.year}</span><span>${p.client}</span></div><div class="project-visual">${projectCarousel(p,i)}</div><div class="project-info"><h3>${p.title}</h3><div class="tags">${p.tags.map(t=>`<span>${tagMarkup(t)}</span>`).join('')}</div><span class="project-arrow">↗</span></div></button>`).join('')}
const allTags=['All',...new Set(projects.flatMap(p=>p.tags).filter(tag=>tag!=='Desktop'&&tag!=='Mobile')),'Desktop','Mobile'];document.querySelector('#filter-bar').innerHTML=allTags.map((tag,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${tag}">${tagMarkup(tag)}</button>`).join('');renderProjects();
document.querySelector('#filter-bar').onclick=e=>{const b=e.target.closest('.filter');if(!b)return;if(b.dataset.filter==='All'){document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='All'));return renderProjects()}document.querySelector('[data-filter="All"]').classList.remove('active');b.classList.toggle('active');const selected=[...document.querySelectorAll('.filter.active')].map(x=>x.dataset.filter).filter(x=>x!=='All');if(!selected.length)document.querySelector('[data-filter="All"]').classList.add('active');renderProjects(selected)};
document.querySelector('#password-form').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#password'),help=document.querySelector('#password-help');if(input.value.toLowerCase()==='zohra'){document.querySelector('#gate').classList.add('exit');setTimeout(()=>{document.querySelector('#gate').classList.add('hidden');document.querySelector('#portfolio').classList.remove('hidden')},550)}else{help.textContent='That password isn’t quite right. Try again.';input.classList.add('error');input.focus()}});
const contactDialog=document.querySelector('#contact-dialog');
const contactTrigger=document.querySelector('.contact-trigger');
const closeContact=()=>{contactDialog.classList.remove('is-open');contactDialog.setAttribute('aria-hidden','true');contactTrigger?.focus()};
contactTrigger?.addEventListener('click',()=>{contactDialog.classList.add('is-open');contactDialog.setAttribute('aria-hidden','false');contactDialog.querySelector('input[name="name"]').focus()});
contactDialog.querySelectorAll('[data-contact-close]').forEach(button=>button.addEventListener('click',closeContact));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&contactDialog.classList.contains('is-open'))closeContact()});
document.querySelector('#contact-form').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget);const subject=`Portfolio inquiry from ${form.get('name')}`;const body=`Name: ${form.get('name')}\nEmail: ${form.get('email')}\n\n${form.get('message')}`;window.location.href=`mailto:jayzohra@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
projectList.addEventListener('click',e=>{const card=e.target.closest('.project-card');if(card)openCaseStudy(projects[card.dataset.project])});
const toParagraphs=items=>items.map(text=>`<p>${text}</p>`).join('');
function openCaseStudy(p){const study=document.querySelector('#case-study');const sectionNav=[['Overview',0],...p.sections.map((s,i)=>[s[0],i+1])];study.innerHTML=`<header class="case-header"><button class="back" aria-label="Back to work">← <span>All work</span></button><a href="#home" class="logo">ZJ<span>®</span></a><span class="case-confidential">Confidential / NDA</span></header><div class="case-hero ${p.color}"><div><p class="eyebrow">${p.client}</p><h1>${p.title}</h1><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div><div class="hero-orbit"><span>${p.client}</span></div></div><div class="case-layout"><aside class="toc"><p class="eyebrow">On this page</p>${sectionNav.map(([s,i])=>`<a href="#section-${i}" class="${i===0?'active':''}">${s}</a>`).join('')}</aside><article class="case-content"><section class="intro-case" id="section-0"><p class="lead">${p.description}</p><dl><div><dt>Role</dt><dd>${p.role}</dd></div><div><dt>Team</dt><dd>${p.team}</dd></div><div><dt>Timeline</dt><dd>${p.timeline}</dd></div></dl></section><section class="video-section"><div class="video-shell"><video autoplay muted loop playsinline><source src="https://cdn.coverr.co/videos/coverr-an-interface-with-graphs-1575/1080p.mp4" type="video/mp4" /></video><div class="video-label"><span>Autoplay prototype placeholder</span><span>Replace with your video</span></div></div></section>${p.sections.map(([title,copy],i)=>`<section class="case-section" id="section-${i+1}"><h2>${title}</h2>${toParagraphs(copy)}<div class="case-image image-${i%4}"><span>Image placeholder / ${title}</span></div></section>`).join('')}</article></div><footer><span>© 2026 Zohra Jayaraman</span><span>Private portfolio</span></footer>`;document.querySelector('#portfolio').classList.add('hidden');study.classList.remove('hidden');window.scrollTo(0,0);study.querySelector('.back').onclick=()=>{study.classList.add('hidden');document.querySelector('#portfolio').classList.remove('hidden');window.scrollTo(0,document.querySelector('#work').offsetTop)};const links=[...study.querySelectorAll('.toc a')],sections=[...study.querySelectorAll('.case-content > section[id]')];const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id))}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>observer.observe(s))}

projects[0].timeline = 'Continuous';
projects[0].tools = 'Sketch, Figma, Jira';
projects[0].description = 'As part of a large project to <strong>modernize their ecosystem</strong>, a large health insurance provider hired 1-5 UX designers at UST Global for 3+ years.<br /><br />The product was an <strong>internal, multi-application dashboard</strong> where health insurance employees would perform various tasks depending on their role.<br /><br />As a Product Designer leading our UX team, with <strong>100+ design handoffs</strong> across <strong>7+ teams</strong> using our design library, I worked to evolve the library into a more consistent and comprehensive <strong>design system</strong> where we could more easily manage and scale design components and collaborate with developers.';
const originalOpenCaseStudy = openCaseStudy;
openCaseStudy = function (project) { originalOpenCaseStudy(project); document.querySelector('#case-study .intro-case').classList.add('case-overview-body'); };

projects[1].description = 'As part of a large project to <strong>modernize their ecosystem</strong>, a large health insurance provider hired 5 UX designers at UST Global for 2 years. With many users having access to multiple applications, we felt a <strong>central entry experience</strong> would tie everything together and help users work more efficiently.';
projects[1].tools = 'Figma, FigJam';
projects[1].sections = [
  ['The challenge',["These challenges applied to every capability, so each team would likely spend multiple sprints customizing and developing solutions in the future. Addressing them ahead of time through a comprehensive entry experience would save capability teams time long term.","<strong>Scattered information:</strong> the client has 35+ customers (plans), and employees may wear multiple hats, use multiple apps, and consult manuals and reference sheets in many tabs. We needed centralization so users could quickly find and reference resources in one place.","<strong>Lack of real-time updates:</strong> important information is spread across applications, so a user may not notice updates relating to patients’ care in time. We needed workflow integration to alert users to multi-application activity and information updates in real time.","<strong>Lack of integration:</strong> users jump across tabs, applications, and views, repeatedly checking each app to respond to requests. We needed visibility of system status to reduce stress and increase confidence and efficiency."]],
  ['Ideation',["After brainstorming with the design team, we identified three opportunities: Education & Help centralization, a Custom Dashboard for workflow integration, and Notifications & Alerts for system-status visibility.","For education and help, we proposed a Help Center to search topics, view FAQs, and submit Service Now tickets; related Guides & Resources; saved Quick Links; and admin management of resources for each capability team.","For the dashboard, we proposed widgets that summarize capability information and let users customize what they see. For notifications, we proposed a capability-notification template, user-managed thresholds, and admin announcements such as maintenance alerts."]],
  ['Solution',["The central entry experience brought together <strong>knowledge, communication, and work</strong> in one integrated starting point. Help content, guides, resources, quick links, dashboard widgets, notifications, and alerts all supported the needs of different plans while keeping the experience cohesive."]],
  ['Learnings & reflection',["Through this project, I strengthened my ability to facilitate workshops, synthesize stakeholder input, and turn a complex, multi-team ecosystem into a clear, practical product direction."]]
];
projects[2].description = 'This case study showcases how I used <strong>user testing</strong> to uncover critical insights that were slowing down task time and contributing to functional issues. By addressing them through <strong>real-time feedback</strong> and an <strong>offline design</strong>, we achieved drastic improvements in task efficiency and success.';
projects[2].tools = 'Figma, FigJam';
projects[2].sections = [
  ['The startup',["Most clothing is made for model body types, leading to poor fit. Custom clothing aims to address this, but it relies on time-consuming and often inaccurate in-person measurements.","TrueToForm uses modern smartphone cameras to capture accurate body measurements in just 30 seconds, from the user’s home. It creates precise digital models that help designers craft better-fitting custom clothing for real bodies."]],
  ['Directing initial focus',["Before I joined TrueToForm, the CEO had interviewed <strong>50+ fashion designers and customers</strong>. The diverse data and use cases left both customers and the team unclear about who the products were for.","I created an affinity map from the interview notes to summarize recurring categories, note follow-up research questions, and brainstorm feature opportunities. These became valuable to revisit during planning and brainstorming.","Combining professions and goals into six personas was too complex for practical use. We reduced them to two simple, generic personas, clarifying user identities and product purpose."]],
  ['Usability testing',["The testing scope was the Scanner’s primary user flow. I conducted in-person usability testing in a fashion school, tailor shop, and participants’ homes, using diverse body types and settings to reduce sampling bias.","<strong>Insight 1:</strong> users had varying interpretations of device placement, body position, and movement timing, causing scans to fail often. Boundary lines, real-time visual and voice feedback, hands-free auto-start, and greater tolerance for minor movement drastically improved task time and scan success.","<strong>Insight 2:</strong> long upload delays and frustrating bugs were caused by unreliable WiFi. An offline design reduced reliance on connection and eliminated many of these issues."]],
  ['Solutions & end result',["Submissions are queued by default, allowing users to leave the app without restarting the scan process whether connected or not. Data is sent in a single submission screen, and a simple status component communicates sharing state.","The primary user flow increased <strong>task success rate by 70%</strong> and decreased <strong>task time by 40%</strong>. Users can complete more accurate scans more successfully, regardless of connection strength."]],
  ['Learnings',["Every company has different starting points, needs, and processes; not every traditional design step is required. I also learned to balance research integrity with the founders’ need for accuracy data, making unbiased observations while supporting business goals."]]
];
projects[2].sections[0][1][1] = '<a href="https://www.truetoform.fit/" target="_blank" rel="noreferrer">TrueToForm</a> uses modern smartphone cameras to capture accurate body measurements in just 30 seconds, from the user’s home. It creates precise digital models that help designers craft better-fitting custom clothing for real bodies.';
projects[2].sections[1][1] = [
  '<span class="case-subhead">Combing Through Market Research for Direction</span>Before I joined TrueToForm, the CEO had interviewed <em>50+ fashion designers and customers</em> in order to explore the problem space. But I noticed that the diverse data and use cases left both customers and the team <strong>unclear about who the products were for</strong>.',
  'To address this, I created an affinity map from her many interview notes, enabling us to <strong>summarize insights for recurring categories</strong>.',
  'I used the affinity maps to:<br /><br />• Categorize and summarize insights<br />• Note potential follow-up research questions<br />• Brainstorm feature opportunities<br /><br />These became <strong>valuable to revisit during future planning and brainstorming.</strong>',
  '<span class="case-subhead">Simplifying Personas for Clarity</span>My UX education had taught me to create highly specific personas. However, combining multiple user professions and goals into <strong>6 personas was just too complex</strong> for practical use.',
  'The Creative Design Lead challenged me to reduce them to <strong>2 simple, generic personas</strong>, making them far more useful for our team and <strong>clarifying user identities and product purpose</strong>.',
  '<strong>Persona #1: Scanner</strong><br />Can include custom clothing customers, fitting models',
  '<strong>Persona #2: Individual Designer</strong><br />Can include tech designers, bespoke custom designers, costume designers for large organizations, costume designers for Film/TV'
];
projects[2].sections[2][1] = [
  'After getting a test plan approved, I traveled to Chicago to conduct in-person usability testing.',
  'The task flow observed was simple. My aim was <strong>to assess ease of use</strong>, <em>especially for the scanning process, where we anticipated the most issues.</em>',
  '<strong>To ensure realistic settings,</strong> I conducted the study in 3 different locations: a fashion school, a tailor shop, and participants’ homes.',
  '<strong>To gather accuracy data,</strong> we enlisted professional tailors to measure participants. We made sure to choose participants with diverse body types in order to gather representative data, test model accuracy, and help train the model. This justified the higher number of participants (~30) compared to the typical 6–10.',
  '<strong>Including diverse locations and body types in the study helped to reduce sampling bias.</strong>'
];

/* Long-form case-study layouts. These intentionally mirror the information hierarchy
   of the corresponding UXFolio studies while keeping the portfolio's own visual system. */
const caseStudyStructure = {
  'Transforming workflow with process and a cohesive design system.': [
    ['Overview', 'summary'], ['The challenge & goals', 'text-image'], ['Refining the design library', 'gallery'], ['Creating a source of truth', 'split'], ['Scaling with governance', 'text-image'], ['Learnings', 'text']
  ],
  'Creating a common entry experience for users across teams.': [
    ['Overview', 'summary'], ['The challenge', 'text-image'], ['Ideation & workshops', 'gallery'], ['The entry experience', 'split'], ['Learnings', 'text']
  ],
  'Utilizing AI-powered 3D tech to enhance real-time experiences.': [
    ['Overview', 'summary'], ['Background research', 'text-image'], ['Usability testing', 'split'], ['Insights & solutions', 'gallery'], ['End result', 'gallery'], ['Learnings', 'text']
  ],
  'Client 360.': [
    ['Overview', 'summary'], ['Problem', 'text'], ['Users & research', 'text'], ['Heuristic evaluation', 'text'], ['Key insights', 'text'], ['Search experience', 'split'], ['Client 360 redesign', 'split'], ['Information architecture', 'text'], ['Before & after', 'text'], ['Next steps', 'text']
  ]
};

function externalLinks(html){
  return html.replace(/<a\b(?![^>]*\bdata-external-icon)([^>]*)>/gi,'<a$1 data-external-icon>');
}
function renderCopyItem(text){
  const html=externalLinks(text);
  const numbered=html.match(/^(.*?)<br\s*\/?>(\s*\d+\.\s+[\s\S]*)$/i);
  if(numbered){
    const parts=numbered[2].split(/<br\s*\/?>(?:\s*<br\s*\/?>)?/i);
    const items=parts.map(part=>part.match(/^\s*\d+\.\s+([\s\S]*)$/)?.[1]).filter(Boolean);
    if(items.length>1)return `<div class="rich-list"><p class="rich-list-title">${numbered[1]}</p><ol>${items.map(item=>`<li>${item}</li>`).join('')}</ol></div>`;
  }
  const bulleted=html.match(/^(.*?)<br\s*\/?>\s*<br\s*\/?>\s*(•\s+[\s\S]*)$/i);
  if(bulleted){
    const [listText,tail='']=bulleted[2].split(/<br\s*\/?>\s*<br\s*\/?>/i);
    const items=listText.split(/<br\s*\/?>/i).map(item=>item.replace(/^\s*•\s*/, '')).filter(Boolean);
    if(items.length>1)return `<div class="rich-list"><p class="rich-list-title">${bulleted[1]}</p><ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul>${tail?`<p>${tail}</p>`:''}</div>`;
  }
  return `<p>${html}</p>`;
}
function placeholder(label, kind='single'){
  if(kind==='gallery') return `<div class="case-media case-gallery" aria-label="Image placeholders for ${label}"><div><span>${label} · image 01</span></div><div><span>${label} · image 02</span></div><div><span>${label} · image 03</span></div></div>`;
  return `<div class="case-media case-media-${kind}" aria-label="Image placeholder for ${label}"><span>${label} · image placeholder</span></div>`;
}
function client360Artifact(label, detail, className=''){
  return `<div class="client360-artifact ${className}" role="img" aria-label="${label} placeholder"><span class="client360-artifact-kicker">Placeholder</span><strong>${label}</strong><p>${detail}</p></div>`;
}
function renderClient360Section(title, copy, layout){
  const paragraphs=(copy||[]).map(renderCopyItem).join('');
  const heading=`<div class="case-section-heading"><p class="eyebrow">${title}</p><h2>${title}</h2></div>`;
  let extra='';
  if(title==='Users & research') extra=client360Artifact('Research findings', 'Add interview themes, usability observations, quotes, and the validated broker persona here.');
  if(title==='Heuristic evaluation') extra=client360Artifact('Heuristic evaluation', 'Add annotated screens and severity-ranked findings from the current experience here.');
  if(title==='Key insights') extra=`<div class="client360-principles"><span>Trust & confidence</span><span>Prioritization & focus</span><span>Personalization at scale</span><span>Decision-first design</span><span>Workflow consolidation</span></div>`;
  if(title==='Search experience') extra=`<figure class="client360-product-shot"><img src="./assets/client-360/search-page.png" alt="Client 360 search results concept" /><figcaption>Search experience · product concept</figcaption></figure>`;
  if(title==='Client 360 redesign') extra=`<figure class="client360-product-shot"><img src="./assets/client-360/jane.png" alt="Client 360 record overview concept" /><figcaption>Client 360 overview · product concept</figcaption></figure>`;
  if(title==='Information architecture') extra=client360Artifact('Sitemap / information architecture', 'Add the validated sitemap, navigation model, and system handoffs here.', 'client360-artifact-tall');
  if(title==='Before & after') extra=`<div class="client360-before-after"><figure><img src="./assets/client-360/before-yasmina.png" alt="Before redesign: Yasmina client record in the existing product" /><figcaption>Before redesign · existing Yasmina record</figcaption></figure>${client360Artifact('After redesign', 'Add the matched Client 360 screen to compare hierarchy, context, and next actions.', 'client360-artifact-after')}</div>`;
  return `<section class="case-section client360-section case-section-${layout}" id="section-${title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}">${heading}<div class="case-copy">${paragraphs}</div>${extra}</section>`;
}
function renderRichSection(title, copy, layout, project){
  if(project?.title==='Client 360.') return renderClient360Section(title,copy,layout);
  const paragraphs = (copy || []).map(text=>text.includes('case-facts')?externalLinks(text):renderCopyItem(text)).join('');
  const media = placeholder(title, layout==='gallery'?'gallery':layout==='split'?'split':'single');
  const heading = `<div class="case-section-heading"><p class="eyebrow">${title}</p><h2>${title}</h2></div>`;
  if(layout==='summary') return `<section class="case-section case-summary" id="section-0">${heading}<div class="case-copy">${paragraphs}</div></section>`;
  if(layout==='text') return `<section class="case-section" id="section-${title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}">${heading}<div class="case-copy">${paragraphs}</div></section>`;
  if(layout==='gallery') return `<section class="case-section case-section-gallery" id="section-${title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}">${heading}<div class="case-copy">${paragraphs}</div>${media}</section>`;
  if(layout==='text-image') return `<section class="case-section case-section-flow" id="section-${title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}">${heading}<div class="case-copy case-copy-flow">${media}${paragraphs}</div></section>`;
  return `<section class="case-section case-section-${layout}" id="section-${title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}">${heading}<div class="case-composition"><div class="case-copy">${paragraphs}</div>${media}</div></section>`;
}

openCaseStudy = function (p) {
  const study=document.querySelector('#case-study');
  const structure=caseStudyStructure[p.title] || [['Summary','summary'],...p.sections.map(s=>[s[0],'text-image'])];
  const sourceSections=p.sections.slice();
  const toc=structure.map((item,index)=>`<a href="#${index===0?'section-0':'section-'+item[0].toLowerCase().replace(/[^a-z0-9]+/g,'-')}" class="${index===0?'active':''}">${item[0]}</a>`).join('');
  const overview=[p.description, `<div class="case-facts"><div><strong>Client</strong><span>${p.client}</span></div><div><strong>My role</strong><span>${p.role}</span></div><div><strong>Worked closely with</strong><span>${p.team}</span></div><div><strong>Timeline</strong><span>${p.timeline}</span></div>${p.tools?`<div><strong>Tools</strong><span>${p.tools}</span></div>`:''}<div><strong>Focus</strong><span>${p.tags.join(', ')}</span></div></div>`];
  const blocks=structure.map(([title,layout],i)=>{
    let copy=i===0?overview:(sourceSections.shift()?.[1]||[]);
    if(p.client==='TrueToForm' && title==='Background research') copy=[...projects[2].sections[0][1],...projects[2].sections[1][1]];
    if(p.client==='TrueToForm' && title==='Usability testing') copy=[...projects[2].sections[2][1]];
    if(p.client==='TrueToForm' && title==='Insights & solutions') copy=[
      '<span class="case-subhead">Insight 1: Varying Interpretations of Instructions</span><strong>The challenge</strong><br />Users had varying understandings of correct device placement, body positioning, and movement timing—<strong>causing scans to fail often</strong>.',
      '<strong>The solutions</strong><br />Boundary lines for positioning, <strong>real-time feedback</strong>, hands-free auto-start, and greater tolerance for minor movement <strong>drastically improved task time and scan success rate.</strong>',
      '<strong>Solutions implemented</strong><br />1. <strong>Gender selection:</strong> revised gender/body-type selection to reduce body-image stress, account for diversity, and increase data accuracy.<br /><br />2. <strong>Starting-position instructions:</strong> replaced the silhouette with boundary lines that made distance and positioning clearer.<br /><br />3. <strong>Scan auto-start:</strong> began capture when the correct position was sensed, so users did not have to interrupt their pose.<br /><br />4. <strong>Wiggle room:</strong> increased the acceptance threshold so small movements while spinning did not fail a scan.',
      '<span class="case-subhead">Insight 2: Bugs Due to Low WiFi Signal</span>Long delays in scan uploads and frustrating functional bugs were <strong>caused by unreliable WiFi</strong> in large public buildings, where most users conducted their scans.',
      '<strong>Designing for unreliable connectivity</strong><br />I began with low-fidelity wireframes to quickly explore flows and present options for team feedback. We realized that submissions could be <strong>queued whenever possible</strong>, reducing reliance on WiFi without interrupting the scan experience.',
      '<strong>Offline design solutions</strong><br />1. <strong>Queue submission:</strong> users can leave the app without restarting the scan process, whether connected or not.<br /><br />2. <strong>Reduce screens and WiFi needs:</strong> share-code validation, avatar submission, and sharing are sent through one queueable submission.<br /><br />3. <strong>Share-status component:</strong> a simple toast communicates whether sharing is in progress or complete.',
      '<strong>Why it mattered</strong><br />The offline design reused more components, increased accessibility for users without reliable WiFi, eliminated connection-related errors such as invalid-ID messages, and let users <strong>multitask instead of waiting on a submission screen.</strong>'
    ];
    if(p.client==='TrueToForm' && title==='End result') copy=['The entire primary user flow—using the solutions in scanning and offline design—<strong>increased primary task success rate by 70%</strong> and <strong>decreased primary task time by 40%</strong>. Now, users can complete more accurate scans more successfully and completely undisrupted, regardless of connection strength.'];
    if(p.client==='TrueToForm' && title==='Learnings') copy=[...projects[2].sections[4][1]];
    return renderRichSection(title,copy,layout,p);
  }).join('');
  const pageCarousel=p.client==='TrueToForm'?`<section class="case-page-carousel" aria-label="TrueToForm product flow"><div class="case-page-carousel-track">${[...ttfFrames,...ttfFrames].map(n=>`<img src="./assets/ttf-cycle-hq/${n}.png" alt="" />`).join('')}</div></section>`:'';
  const pageVideo=p.title==='Client 360.'?`<section class="case-page-video" aria-label="Client 360 product preview"><video src="./assets/client-360/client-360.mov" autoplay muted loop playsinline preload="metadata" controls></video></section>`:'';
  study.innerHTML=`<header class="case-header"><button class="back" aria-label="Back to work"><span class="back-icon" aria-hidden="true">←</span><span>All work</span></button><a href="#home" class="logo">ZJ<span>®</span></a><span class="case-confidential">Confidential</span></header><div class="case-hero ${p.color}"><div><p class="eyebrow">${p.client}</p><h1>${p.title}</h1><div class="tags">${p.tags.map(t=>`<span>${tagMarkup(t)}</span>`).join('')}</div></div><div class="hero-orbit"><span>${p.client}</span></div></div><div class="case-layout"><aside class="toc"><p class="eyebrow">On this page</p>${toc}</aside><article class="case-content">${pageVideo}${pageCarousel}${blocks}</article></div><footer><span>© 2026 Zohra Jayaraman</span><span>Product Designer Portfolio</span></footer>`;
  document.querySelector('#portfolio').classList.add('hidden');study.classList.remove('hidden');window.scrollTo(0,0);
  study.querySelector('.back').onclick=()=>{study.classList.add('hidden');document.querySelector('#portfolio').classList.remove('hidden');window.scrollTo(0,document.querySelector('#work').offsetTop)};
  const links=[...study.querySelectorAll('.toc a')],sections=[...study.querySelectorAll('.case-content > section[id]')];
  const updateActiveToc=()=>{
    const readingLine=window.innerHeight*.38;
    let current=sections[0];
    sections.forEach(section=>{if(section.getBoundingClientRect().top<=readingLine)current=section});
    links.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${current.id}`));
  };
  if(study._tocScrollHandler)window.removeEventListener('scroll',study._tocScrollHandler);
  study._tocScrollHandler=updateActiveToc;
  window.addEventListener('scroll',updateActiveToc,{passive:true});
  updateActiveToc();
};
